name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: node
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
