name: "Use specific version"
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: "10.0.0"
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
        if [ $(node -v) != "v10.0.0" ]; then
          exit 1;
        fi
